<?php

/**
 * @file
 * Drupal Module: ReachEdge.
 *
 * Adds the required Javascript to all your Drupal pages to allow tracking by
 * the ReachLocal package.
 *
 * @author: REDrupalPlugin
 */

/**
 * Define default path exclusion list to remove tracking from admin pages.
 */
define('REACHEDGE_PAGES', "admin\nadmin/*\nbatch\nnode/add*\nnode/*/*\nuser/*/*");

/**
 * Implements hook_menu().
 */
function reachedge_menu() {

  $items['admin/config/system/reachedge'] = array(
    'title' => 'ReachEdge',
    'description' => 'Configure tracking behavior to get insights into your website traffic and marketing effectiveness.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('reachedge_admin_settings_form'),
    'access arguments' => array('administer reachedge tracking'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'reachedge.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function reachedge_permission() {

  return array(
    'administer reachedge tracking' => array(
      'title' => t('Administer ReachEdge'),
      'description' => t('Perform maintenance tasks for ReachEdge.'),
    ),
  );
}


/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * path @param
 *   Which path of the site we're using to display help
 * arg @param
 *   Array that holds the current path as returned from arg() function
 */
function reachedge_help($path, $arg) {

  switch ($path) {
    case 'admin/help#reachedge':
      return t('<a href="@reachedge">ReachLocal</a> is a ..............', array('@reachedge' => 'http://www.reachlocal.com'));
  }
}

/**
 * Implements hook_page_alter().
 */
function reachedge_page_alter(&$page) {

  // Global $user;.
  $id = variable_get('reachedge_id', '');

  if (preg_match('/^[A-Z0-9]{8}(-[A-Z0-9]{4}){3}-[A-Z0-9]{12}$/i', $id) && _reachedge_visibility_pages()) {

    // Build tracker code.
    $script = 'var rl_siteid = "';
    $script .= $id;
    $script .= '";';

    drupal_add_js($script, array('scope' => 'header', 'type' => 'inline'));
    drupal_add_js('//cdn.rlets.com/capture_static/mms/mms.js', array('scope' => 'header', 'type' => 'external'));

  }

}

/**
 * Determine which pages should run the ReachEdge Capture Code.
 *
 * Based on visibility setting this function returns TRUE if ReachEdge Capture
 * code should be added to the current page, otherwise FALSE.
 */
function _reachedge_visibility_pages() {

  static $page_match;

  // Cache visibility result if function is called more than once.
  if (!isset($page_match)) {

    $visibility = variable_get('reachedge_visibility_pages', 0);
    $setting_pages = variable_get('reachedge_pages', REACHEDGE_PAGES);

    // Match path if necessary.
    if (!empty($setting_pages)) {
      // Convert path to lowercase. This allows comparison of the same path
      // with different case. Ex: /Page, /page, /PAGE.
      $pages = drupal_strtolower($setting_pages);
      if ($visibility < 2) {
        // Convert the Drupal path to lowercase.
        $path = drupal_strtolower(drupal_get_path_alias($_GET['q']));
        // Compare the lowercase internal and lowercase path alias (if any).
        $page_match = drupal_match_path($path, $pages);
        if ($path != $_GET['q']) {
          $page_match = $page_match || drupal_match_path($_GET['q'], $pages);
        }
        // When $visibility has a value of 0, the tracking code is displayed on
        // all pages except those listed in $pages. When set to 1, it
        // is displayed only on those pages listed in $pages.
        $page_match = !($visibility xor $page_match);
      }
      elseif (module_exists('php')) {
        $page_match = php_eval($setting_pages);
      }
      else {
        $page_match = FALSE;
      }
    }
    else {
      $page_match = TRUE;
    }

  }
  return $page_match;
}
